import type { Question } from "./types";

export const derivativesQuestions: Question[] = [
  {
    id: "derivatives-forward-001",
    kind: "truefalse",
    chapter: "derivatives",
    sectionId: "linear",
    conceptSlugs: ["forward-price", "forward-contract"],
    difficulty: 3,
    skill: "trap",
    stem: "远期价格 $F$ 是市场对未来即期的期望，所以 $F$ 偏高就该做空远期。",
    answer: false,
    explanation:
      "$F$ 是使合约现值刚为零的无套利价格：$F=S e^{(r-q)T}$。它不是对未来即期的期望，除非风险溢价为零。把 $F$ 当预测，是把无套利当成观点。",
  },
  {
    id: "derivatives-parity-001",
    kind: "single",
    chapter: "derivatives",
    sectionId: "options",
    conceptSlugs: ["put-call-parity", "call-option", "put-option"],
    difficulty: 2,
    skill: "calculation",
    stem: "欧式期权、无红利，看涨—看跌平价 $C-P=S-K e^{-rT}$。若左边明显大于右边（忽略摩擦），无套利方向是？",
    choices: [
      { id: "a", text: "买 call、卖 put、空标的、多债券（合成空头远期 vs 贵的期权组合）" },
      { id: "b", text: "只买 call，因为 call 被低估" },
      { id: "c", text: "平价对美式也严格成立，所以不用管" },
      { id: "d", text: "加大 VIX 仓位" },
    ],
    answer: "a",
    explanation:
      "平价强制欧式看涨、看跌与远期一致。$C-P$ 太贵就卖这个合成远期、买真正的债券+股票复制（符号随你写的平价形式而定）。这是期权第一恒等式，原文完全没写。美式因提前行权，平价变成不等式。",
  },
  {
    id: "derivatives-longput-001",
    kind: "single",
    chapter: "derivatives",
    sectionId: "options",
    conceptSlugs: ["put-option", "long-put"],
    difficulty: 3,
    skill: "trap",
    stem: "「看跌期权」和「买入看跌（long put）」可以当成同一个词条来用。",
    choices: [
      { id: "a", text: "可以：都是看跌" },
      { id: "b", text: "不可以。合约定义了权利；long put 是仓位——损失有限、负 Theta、正 Vega，卖出看跌完全不同" },
      { id: "c", text: "只有美式才需要区分" },
      { id: "d", text: "long put 就是卖出看跌" },
    ],
    answer: "b",
    explanation:
      "原文把合约与 long put 仓位混在一篇。权利、多头、空头是三件事。卖出看跌的风险图像和买入看跌相反。",
  },
  {
    id: "derivatives-deltahedge-001",
    kind: "single",
    chapter: "derivatives",
    sectionId: "greeks",
    conceptSlugs: ["delta-hedging", "delta", "gamma", "implied-vol"],
    difficulty: 2,
    skill: "recall",
    stem: "Delta 对冲之后，你实际上在交易什么？",
    choices: [
      { id: "a", text: "股票的方向，因为还持有标的" },
      { id: "b", text: "方向被拿走，剩下 Gamma / Vega / Theta——已实现波动对隐含波动" },
      { id: "c", text: "无风险利率本身" },
      { id: "d", text: "公司的信用评级" },
    ],
    answer: "b",
    explanation:
      "Delta 是复制组合里的标的数量。离散对冲、跳跃、价差，就是 PnL。这才是波动率交易。",
  },
  {
    id: "derivatives-dneutral-001",
    kind: "truefalse",
    chapter: "derivatives",
    sectionId: "greeks",
    conceptSlugs: ["delta-neutral", "gamma"],
    difficulty: 3,
    skill: "trap",
    stem: "组合已经 Delta 中性，因此是无风险的。",
    answer: false,
    explanation:
      "标的只能对冲 Delta。还剩 Gamma、Vega、Theta、跳空和融资。Delta 中性不是无风险。",
  },
  {
    id: "derivatives-gamma-001",
    kind: "single",
    chapter: "derivatives",
    sectionId: "greeks",
    conceptSlugs: ["gamma", "gamma-hedging"],
    difficulty: 2,
    skill: "recall",
    stem: "净多 Gamma 的期权组合，通常？",
    choices: [
      { id: "a", text: "怕大动、喜欢时间流逝" },
      { id: "b", text: "喜大动、怕时间（负 Theta）；对冲 Gamma 必须用别的期权" },
      { id: "c", text: "与 Vega 无关，可以忽略隐含波动" },
      { id: "d", text: "等价于持有期货" },
    ],
    answer: "b",
    explanation:
      "Gamma 是 Delta 的导数、价格的凸性。多 Gamma 在标的大动时赚凸性，用 Theta 付租金。期货近似线性，给不了 Gamma。",
  },
  {
    id: "derivatives-forward-calc-001",
    kind: "single",
    chapter: "derivatives",
    sectionId: "linear",
    conceptSlugs: ["forward-price"],
    difficulty: 2,
    skill: "calculation",
    stem: "无红利股票，$S_0=100$，$r=5\\%$（连续），$T=1$ 年。无套利远期价格最接近？",
    choices: [
      { id: "a", text: "$100$，因为远期不是预测" },
      { id: "b", text: "$100\\,e^{0.05}\\approx 105.1$" },
      { id: "c", text: "$100\\times 1.05^{252}$" },
      { id: "d", text: "$100\\,e^{-0.05}\\approx 95.1$，必须贴现" },
    ],
    answer: "b",
    explanation:
      "$F_{0,T}=S_0 e^{(r-q)T}$，$q=0$ 故 $100 e^{0.05}$。$F$ 不是期望；95.1 把方向乘反了。不要把交易日数塞进已经是「一年」的 $T$。",
  },
  {
    id: "derivatives-futures-001",
    kind: "single",
    chapter: "derivatives",
    sectionId: "linear",
    conceptSlugs: ["futures", "forward-contract", "basis"],
    difficulty: 2,
    skill: "recall",
    stem: "期货相对远期，实务 PnL 上最重要的差别通常是？",
    choices: [
      { id: "a", text: "期货没有标的" },
      { id: "b", text: "标准化、每日盯市，对手方风险换成清算所与保证金；基差与展期是实盘主要来源" },
      { id: "c", text: "期货保证盈利" },
      { id: "d", text: "远期才需要保证金，期货不需要" },
    ],
    answer: "b",
    explanation:
      "远期场外、到期履行。期货盯市把路径变成每日现金流。回测用远期公式去套期货，会漏掉融资和展期。",
  },
  {
    id: "derivatives-iv-001",
    kind: "truefalse",
    chapter: "derivatives",
    sectionId: "greeks",
    conceptSlugs: ["implied-vol", "volatility-smile", "vol-arb"],
    difficulty: 3,
    skill: "trap",
    stem: "隐含波动是对未来已实现波动的无偏预测；微笑/偏斜只是流动性噪音。",
    answer: false,
    explanation:
      "IV 是价格的报价方式。微笑/偏斜否证了常数 $\\sigma$。波动率「套利」交易 IV vs RV，名字里的 arbitrage 名不副实。",
  },
  {
    id: "derivatives-duration-001",
    kind: "single",
    chapter: "derivatives",
    sectionId: "greeks",
    conceptSlugs: ["duration", "convexity", "delta"],
    difficulty: 2,
    skill: "recall",
    stem: "固收里与期权 Delta / Gamma 最对应的一对是？",
    choices: [
      { id: "a", text: "票息 / 面值" },
      { id: "b", text: "久期（一阶）/ 凸性（二阶）" },
      { id: "c", text: "评级 / 展望" },
      { id: "d", text: "YTM / 当前收益率，二者都是一阶" },
    ],
    answer: "b",
    explanation:
      "久期是对利率的一阶敏感度，凸性是二阶。和 Delta–Gamma 是同一套泰勒展开语言。",
  },
  {
    id: "derivatives-straddle-001",
    kind: "truefalse",
    chapter: "derivatives",
    sectionId: "options",
    conceptSlugs: ["straddle", "implied-vol"],
    difficulty: 2,
    skill: "recall",
    stem: "买入跨式（straddle）是最干净的波动观点之一：方向尽量中性，赌的是实现波动够不够付期权金。",
    answer: true,
    explanation:
      "跨式把方向对冲进两只期权。你付 Theta，买 Gamma/Vega。二元期权报价的则是风险中性概率，不是同一件事。",
  },
  {
    id: "derivatives-merton-001",
    kind: "single",
    chapter: "derivatives",
    sectionId: "greeks",
    conceptSlugs: ["merton-model", "call-option"],
    difficulty: 2,
    skill: "recall",
    stem: "默顿结构模型把公司股权写成？",
    choices: [
      { id: "a", text: "对债务的看跌期权" },
      { id: "b", text: "企业资产的看涨期权：$E=V N(d_1)-K e^{-rT}N(d_2)$，其中 $\\sigma$ 是资产波动" },
      { id: "c", text: "股票收益的正态性检验" },
      { id: "d", text: "对 VIX 的期货" },
    ],
    answer: "b",
    explanation:
      "信用与期权是同一套数学。原文把默顿放在统计学，并把 $\\sigma$ 写成股票波动率。",
  },
];
