import type { Question } from "./types";

export const macroQuestions: Question[] = [
  {
    id: "macro-discount-001",
    kind: "single",
    chapter: "macro",
    sectionId: "policy",
    conceptSlugs: ["discount-rate-fed", "discount-rate-dcf"],
    difficulty: 3,
    skill: "trap",
    stem: "美联储的贴现窗口利率（discount rate），和估值里把现金流贴现的贴现率，是一回事吗？",
    choices: [
      { id: "a", text: "是：都叫贴现率，数值也应当相同" },
      { id: "b", text: "不是。窗口利率是最后贷款人工具；DCF 贴现率要匹配现金流风险" },
      { id: "c", text: "窗口利率就是 WACC" },
      { id: "d", text: "只有在倒挂时两者才相等" },
    ],
    answer: "b",
    explanation:
      "贴现窗口通常高于市场、带污名，是流动性工具。DCF 贴现率是风险调整后的机会成本（CAPM 成本或 WACC）。原文把这两件事写在同一篇。",
  },
  {
    id: "macro-surprise-001",
    kind: "truefalse",
    chapter: "macro",
    sectionId: "real",
    conceptSlugs: ["inflation", "gdp", "unemployment"],
    difficulty: 2,
    skill: "recall",
    stem: "资产价格交易的是数据相对预期的意外，而不是教科书上的水平本身。",
    answer: true,
    explanation:
      "增长、通胀、失业的水平大多已进价格。真正移动贴现率和风险偏好的，是意外以及政策反应函数怎么读这段意外。",
  },
  {
    id: "macro-deficit-001",
    kind: "truefalse",
    chapter: "macro",
    sectionId: "open",
    conceptSlugs: ["trade-deficit"],
    difficulty: 3,
    skill: "trap",
    stem: "贸易逆差表示「国家在亏钱」，所以逆差扩大时该国资产必须下跌。",
    answer: false,
    explanation:
      "贸易逆差是储蓄—投资缺口的镜子，对应资本流入，不是「国家亏钱」。逆差本身不是空头信号；要问的是资本流入买的是什么、能持续多久。",
  },
  {
    id: "macro-curve-001",
    kind: "single",
    chapter: "macro",
    sectionId: "policy",
    conceptSlugs: ["inverted-yield-curve", "interest-rate"],
    difficulty: 2,
    skill: "recall",
    stem: "收益率曲线倒挂常被当作衰退信号。使用时最需要记住的是？",
    choices: [
      { id: "a", text: "倒挂出现后下一个交易日就会衰退" },
      { id: "b", text: "机制是预期未来短端下降或期限溢价为负；时滞极不稳定，2s10s 与 3m10y 结论可以不同" },
      { id: "c", text: "倒挂证明长期利率被操纵，与衰退无关" },
      { id: "d", text: "只有 10Y 绝对水平重要，斜率无意义" },
    ],
    answer: "b",
    explanation:
      "倒挂是有信息的，但不是交易日历。期限溢价为负时，倒挂可以在没有衰退的情况下出现。",
  },
  {
    id: "macro-qe-001",
    kind: "single",
    chapter: "macro",
    sectionId: "policy",
    conceptSlugs: ["qe", "open-market-operations", "federal-funds-rate"],
    difficulty: 2,
    skill: "recall",
    stem: "公开市场操作和量化宽松，分工上最接近？",
    choices: [
      { id: "a", text: "OMO 把政策利率做到市场上；QE 是利率触底后买久期、压期限溢价" },
      { id: "b", text: "QE 就是把联邦基金利率调到负值" },
      { id: "c", text: "OMO 只买卖股票，QE 只买卖外汇" },
      { id: "d", text: "两者都是财政政策" },
    ],
    answer: "a",
    explanation:
      "短端锚是联邦基金利率；市场交易的是路径预期与点阵图之差。QE 改变的是资产负债表和期限溢价，不是「另一种降息口令」。",
  },
  {
    id: "macro-gdp-001",
    kind: "single",
    chapter: "macro",
    sectionId: "real",
    conceptSlugs: ["gdp", "gnp"],
    difficulty: 2,
    skill: "recall",
    stem: "GDP 与 GNP 的核心差别是？",
    choices: [
      { id: "a", text: "GDP 含通胀，GNP 不含" },
      { id: "b", text: "GDP 是境内最终产出；GNP 加上海外净要素收入" },
      { id: "c", text: "GNP 只统计国企" },
      { id: "d", text: "没有差别，只是旧称" },
    ],
    answer: "b",
    explanation:
      "长期增长由劳动力、资本、生产率决定；指数与因子的一年表现常常是周期位置。先分清你在量哪一块产出。",
  },
  {
    id: "macro-duration-001",
    kind: "truefalse",
    chapter: "macro",
    sectionId: "real",
    conceptSlugs: ["inflation", "interest-rate"],
    difficulty: 2,
    skill: "recall",
    stem: "成长股是长久期资产，因此对贴现率（从而对通胀意外）更敏感。",
    answer: true,
    explanation:
      "通胀把名义利率拆成实际利率加预期。现金流越远，贴现率动一点，现值动得越大。这是宏观进入成长股的通道。",
  },
  {
    id: "macro-advantage-001",
    kind: "single",
    chapter: "macro",
    sectionId: "open",
    conceptSlugs: ["comparative-advantage", "absolute-advantage"],
    difficulty: 2,
    skill: "recall",
    stem: "贸易的逻辑是比较优势。它强调的是？",
    choices: [
      { id: "a", text: "谁的绝对成本更低谁就该生产一切" },
      { id: "b", text: "机会成本：即使一方样样更强，仍应按相对成本分工" },
      { id: "c", text: "关税总能提高本国福利" },
      { id: "d", text: "汇率必须固定，否则没有比较优势" },
    ],
    answer: "b",
    explanation:
      "绝对优势回答「谁更能做」；比较优势回答「谁放弃得更少」。关税提高进口价格、保护部分生产者、伤害下游。",
  },
  {
    id: "macro-phillips-001",
    kind: "truefalse",
    chapter: "macro",
    sectionId: "real",
    conceptSlugs: ["phillips-curve", "unemployment", "inflation"],
    difficulty: 3,
    skill: "trap",
    stem: "菲利普斯曲线给出失业—通胀权衡，因此可以当成稳定的交易法则：失业率一降就做多通胀。",
    answer: false,
    explanation:
      "曲线会移动，预期、供给冲击都会改写权衡。它是直觉框架，不是可估计的高频信号。",
  },
  {
    id: "macro-fedfunds-001",
    kind: "multi",
    chapter: "macro",
    sectionId: "policy",
    conceptSlugs: ["federal-funds-rate", "monetary-policy", "interest-rate"],
    difficulty: 2,
    skill: "recall",
    stem: "谈「利率」时必须声明口径。下列哪些维度是必需的？（多选）",
    choices: [
      { id: "a", text: "名义 / 实际" },
      { id: "b", text: "短端 / 长端，即期 / 远期" },
      { id: "c", text: "无风险 / 含信用，以及年化惯例" },
      { id: "d", text: "该利率今天是否上了热搜" },
    ],
    answer: ["a", "b", "c"],
    explanation:
      "同一个词「利率」可以指完全不同的东西。联邦基金利率是美元隔夜锚；市场交易路径，不是只交易今天的水平。",
  },
];
