import type { Question } from "./types";

export const marketsQuestions: Question[] = [
  {
    id: "markets-treasury-001",
    kind: "single",
    chapter: "markets",
    sectionId: "fi-fx",
    conceptSlugs: ["treasury-bill", "treasury-note", "treasury-bond"],
    difficulty: 3,
    skill: "trap",
    stem: "中文「国库券」在美债语境下，最接近哪一类？",
    choices: [
      { id: "a", text: "Treasury Notes：2–10 年附息" },
      { id: "b", text: "Treasury Bills：≤1 年贴现、无票息" },
      { id: "c", text: "Treasury Bonds：20/30 年长端" },
      { id: "d", text: "三者没有区别，只是中文译名不同" },
    ],
    answer: "b",
    explanation:
      "原文把「国库券」标成 Treasury Notes。中文国库券更接近 T-Bill（短期贴现）。T-Note 是中期附息，10Y 是全球基准；T-Bond 是长端。报价惯例也不同。",
  },
  {
    id: "markets-held-001",
    kind: "truefalse",
    chapter: "markets",
    sectionId: "micro",
    conceptSlugs: ["held-order", "ioc-order"],
    difficulty: 3,
    skill: "trap",
    stem: "Held order 就是「限时订单」：到点不成交就过期，和 Day / GTD 一类。",
    answer: false,
    explanation:
      "Held order 是经纪术语：必须立即执行、几乎无价格裁量。它不是 time-in-force。真正的时效指令是 IOC/FOK/Day/GTD。原文中文标题是错的。",
  },
  {
    id: "markets-tplusone-001",
    kind: "single",
    chapter: "markets",
    sectionId: "micro",
    conceptSlugs: ["t-plus-one"],
    difficulty: 3,
    skill: "trap",
    stem: "A 股常说的 T+1，和美股 T+1 结算，主要差别是？",
    choices: [
      { id: "a", text: "没有差别，都是隔日才能卖" },
      { id: "b", text: "A 股 T+1 往往指当日买入不可卖出；美股 T+1 是结算周期，仍可当日回转" },
      { id: "c", text: "美股 T+1 禁止日内交易" },
      { id: "d", text: "A 股 T+1 只影响债券" },
    ],
    answer: "b",
    explanation:
      "回测和容量必须写清约束。把美股的结算 T+1 当成 A 股的「当天买了不能卖」，会系统性高估换手策略。",
  },
  {
    id: "markets-orders-001",
    kind: "single",
    chapter: "markets",
    sectionId: "micro",
    conceptSlugs: ["market-order", "limit-order", "limit-order-book"],
    difficulty: 2,
    skill: "recall",
    stem: "市价单和限价单，分别锁住的是什么？",
    choices: [
      { id: "a", text: "市价单锁价格，限价单锁时间" },
      { id: "b", text: "市价单确定时间、不确定价格；限价单确定最差价格、不确定能否成交" },
      { id: "c", text: "两者在电子盘上没有区别" },
      { id: "d", text: "限价单一定吃流动性，市价单一定提供流动性" },
    ],
    answer: "b",
    explanation:
      "你成交的是订单簿上的报价。限价单提供流动性、承担逆向选择。回测用 last/close 会系统性高估市价单的可成交价格。",
  },
  {
    id: "markets-venues-001",
    kind: "single",
    chapter: "markets",
    sectionId: "venues",
    conceptSlugs: ["primary-market", "secondary-market"],
    difficulty: 2,
    skill: "recall",
    stem: "量化策略几乎都在二级市场交易。一级市场仍然重要，是因为？",
    choices: [
      { id: "a", text: "一级市场才有 K 线" },
      { id: "b", text: "发行供给、锁定期、拍卖机制会改变随后的波动与因子" },
      { id: "c", text: "二级市场没有价格发现" },
      { id: "d", text: "一级市场的成交价等于理论价值" },
    ],
    answer: "b",
    explanation:
      "一级是发行人融资（IPO、增发、国债拍卖）；二级是投资者转手、价格发现发生的地方。供给冲击会进入你随后交易的分布。",
  },
  {
    id: "markets-short-001",
    kind: "truefalse",
    chapter: "markets",
    sectionId: "micro",
    conceptSlugs: ["short-selling", "short-position"],
    difficulty: 2,
    skill: "trap",
    stem: "回测里假设可以免费、无限卖空，对多空股票策略通常只是无伤大雅的简化。",
    answer: false,
    explanation:
      "卖空利润有限、亏损理论上无界，还有借券费与召回。免费无限卖空是回测里最常见的谎言之一，会把不可交易的空头写成 alpha。",
  },
  {
    id: "markets-quote-001",
    kind: "truefalse",
    chapter: "markets",
    sectionId: "micro",
    conceptSlugs: ["quotation", "bid-ask", "liquidity"],
    difficulty: 3,
    skill: "trap",
    stem: "用收盘价/最新成交价回测，再假设以该价格成交，通常会高估策略的可实现收益。",
    answer: true,
    explanation:
      "报价是 bid/ask 与数量。你真正能吃到的是账簿上的价，不是 K 线收盘。忽略价差、冲击和能否成交，会系统性乐观。",
  },
  {
    id: "markets-ioc-001",
    kind: "single",
    chapter: "markets",
    sectionId: "micro",
    conceptSlugs: ["ioc-order", "limit-order"],
    difficulty: 2,
    skill: "recall",
    stem: "IOC 订单的行为是？",
    choices: [
      { id: "a", text: "挂在账簿上直到收盘" },
      { id: "b", text: "能成交的立刻成交，剩余撤销" },
      { id: "c", text: "必须全部成交，否则整单撤销且经纪没有价格裁量——即 held order" },
      { id: "d", text: "保证以收盘价成交" },
    ],
    answer: "b",
    explanation:
      "IOC = Immediate-or-Cancel。FOK 才是全部成交否则取消。Held order 是经纪执行约束，不是 IOC。",
  },
  {
    id: "markets-liquidity-001",
    kind: "multi",
    chapter: "markets",
    sectionId: "micro",
    conceptSlugs: ["liquidity"],
    difficulty: 2,
    skill: "recall",
    stem: "流动性不只是「能卖掉」。它至少还包括哪些维度？（多选）",
    choices: [
      { id: "a", text: "价差" },
      { id: "b", text: "深度" },
      { id: "c", text: "股票简称是否好记" },
      { id: "d", text: "弹性与即时性" },
    ],
    answer: ["a", "b", "d"],
    explanation:
      "价差、深度、弹性、即时性。资产流动性与融资流动性还会互相强化——这是杠杆策略在压力里爆掉的通道。",
  },
  {
    id: "markets-pb-001",
    kind: "single",
    chapter: "markets",
    sectionId: "micro",
    conceptSlugs: ["prime-brokerage", "margin", "dealer"],
    difficulty: 2,
    skill: "recall",
    stem: "对冲基金的杠杆、融券、托管，通常走的是？",
    choices: [
      { id: "a", text: "交易所的 IPO 通道" },
      { id: "b", text: "Prime Broker；保证金是杠杆的实现，爆仓是保证金公式被击穿" },
      { id: "c", text: "只需一个普通零售券商的市价单" },
      { id: "d", text: "中央银行贴现窗口" },
    ],
    answer: "b",
    explanation:
      "交易商用自己的账户吃价差。基金的融资融券与托管在 PB。爆仓具有路径依赖，不是「平均波动」能概括的。",
  },
];
