import type { Question } from "./types";

export const pricingQuestions: Question[] = [
  {
    id: "pricing-beta-001",
    kind: "truefalse",
    chapter: "pricing",
    sectionId: "emh-capm",
    conceptSlugs: ["beta", "capm"],
    difficulty: 3,
    skill: "trap",
    stem: "β = 1 的股票「不增加任何风险」。",
    answer: false,
    explanation:
      "β=1 表示与市场同步的系统风险，加入组合会带入市场风险；只是没有额外的相对波动。原文这句话是错的。要区分系统风险、特异质风险与相对基准的残差。",
  },
  {
    id: "pricing-alpha-001",
    kind: "single",
    chapter: "pricing",
    sectionId: "emh-capm",
    conceptSlugs: ["alpha", "capm", "multi-factor-model"],
    difficulty: 3,
    skill: "trap",
    stem: "某策略相对 CAPM 有正 α。下列哪句最准确？",
    choices: [
      { id: "a", text: "这就是「真 alpha」，换模型也不会变" },
      { id: "b", text: "α 是相对所选择模型的截距；换因子模型，α 就变" },
      { id: "c", text: "α 等于夏普" },
      { id: "d", text: "α 为正就可以忽略成本" },
    ],
    answer: "b",
    explanation:
      "没有明确的基准与因子，就没有 alpha，只有「赚了钱」。样本内 α 很容易挖；真正的 α 必须样本外、扣成本、扣多重检验。",
  },
  {
    id: "pricing-capm-001",
    kind: "single",
    chapter: "pricing",
    sectionId: "emh-capm",
    conceptSlugs: ["capm", "beta"],
    difficulty: 2,
    skill: "recall",
    stem: "CAPM 说的是？",
    choices: [
      { id: "a", text: "期望超额与特质波动成正比" },
      { id: "b", text: "期望超额与市场 β 成正比：$\\mathbb{E}[R_i]-r_f=\\beta_i(\\mathbb{E}[R_m]-r_f)$" },
      { id: "c", text: "价格已反映所有信息，因此 β 必须为 0" },
      { id: "d", text: "高波动必须高 β" },
    ],
    answer: "b",
    explanation:
      "β 是回归斜率，是系统暴露，不是波动率本身。波动大但与市场无关，β 可以低。",
  },
  {
    id: "pricing-unlevered-001",
    kind: "single",
    chapter: "pricing",
    sectionId: "emh-capm",
    conceptSlugs: ["unlevered-beta", "beta", "leverage"],
    difficulty: 2,
    skill: "recall",
    stem: "无杠杆 β 主要用来？",
    choices: [
      { id: "a", text: "替代 WACC" },
      { id: "b", text: "跨资本结构比较业务风险；高杠杆公司的权益 β 自然更高" },
      { id: "c", text: "证明公司没有财务风险" },
      { id: "d", text: "把期权的 Delta 换算成年化" },
    ],
    answer: "b",
    explanation:
      "权益 β 混了业务风险和财务杠杆。比较两家公司的「生意有多顺周期」，要用无杠杆 β。",
  },
  {
    id: "pricing-vol-beta-001",
    kind: "truefalse",
    chapter: "pricing",
    sectionId: "risk-vol",
    conceptSlugs: ["volatility", "beta"],
    difficulty: 3,
    skill: "trap",
    stem: "高波动的股票一定是高 β 股票。",
    answer: false,
    explanation:
      "高波动 ≠ 高 β。β 还取决于与市场的相关。一只自己乱跳、与指数无关的股票，σ 可以很大、β 可以很低。",
  },
  {
    id: "pricing-hedge-001",
    kind: "truefalse",
    chapter: "pricing",
    sectionId: "risk-vol",
    conceptSlugs: ["hedge"],
    difficulty: 2,
    skill: "trap",
    stem: "对冲是免费保险：做了对冲之后就没有风险了。",
    answer: false,
    explanation:
      "对冲是转移某一因子，不是免费保险。完美对冲只在模型里。你付的是基差、展期、缺口和模型风险。",
  },
  {
    id: "pricing-vix-001",
    kind: "truefalse",
    chapter: "pricing",
    sectionId: "risk-vol",
    conceptSlugs: ["vix", "implied-vol"],
    difficulty: 3,
    skill: "trap",
    stem: "VIX 是 30 天隐含方差的指数，本身可以直接当标的来买卖，价格等于未来已实现波动。",
    answer: false,
    explanation:
      "VIX 本身不可直接交易；期货和期权才是交易工具，还必须通过期限结构来理解。隐含波动是报价方式，不是无偏预测。",
  },
  {
    id: "pricing-emh-001",
    kind: "single",
    chapter: "pricing",
    sectionId: "emh-capm",
    conceptSlugs: ["emh"],
    difficulty: 2,
    skill: "recall",
    stem: "有效市场假说（EMH）真正说的是？",
    choices: [
      { id: "a", text: "不可能赚钱，量化没有意义" },
      { id: "b", text: "价格已反映某个信息集；扣掉风险、成本、选择性报告后，没有免费午餐" },
      { id: "c", text: "技术分析永远有效" },
      { id: "d", text: "所有可预测性都是无效" },
    ],
    answer: "b",
    explanation:
      "可预测性可以是风险溢价，也可以是摩擦。EMH 不是「不能赚钱」，是「没有不承担风险或成本的免费午餐」。",
  },
  {
    id: "pricing-factor-001",
    kind: "single",
    chapter: "pricing",
    sectionId: "factors",
    conceptSlugs: ["factor-investing", "fama-french", "multi-factor-model"],
    difficulty: 2,
    skill: "recall",
    stem: "面对一个「很能赚钱」的选股策略，多因子框架下第一句该问的是？",
    choices: [
      { id: "a", text: "作者的夏普是多少" },
      { id: "b", text: "它实际加载了哪些共同因子（是不是小盘价值等），再谈残差 α" },
      { id: "c", text: "要不要立刻加杠杆" },
      { id: "d", text: "是否符合格雷厄姆的原话" },
    ],
    answer: "b",
    explanation:
      "先问策略是不是 SMB/HML/盈利/投资。因子定义（如何分组）会改变结论。发表后衰减、拥挤、定义套利是真实风险。",
  },
  {
    id: "pricing-vol-ann-001",
    kind: "single",
    chapter: "pricing",
    sectionId: "risk-vol",
    conceptSlugs: ["volatility"],
    difficulty: 2,
    skill: "calculation",
    stem: "把日收益标准差年化成「年波动」时，常用 $\\times\\sqrt{252}$。这个做法默认了什么？",
    choices: [
      { id: "a", text: "收益独立（至少不相关），方差可加" },
      { id: "b", text: "收益必须正态" },
      { id: "c", text: "一年恰好 365 个交易日" },
      { id: "d", text: "波动率等于 β" },
    ],
    answer: "a",
    explanation:
      "独立时方差按时间线性加，波动按平方根。有波动聚集、自相关时，$\\sqrt{252}$ 只是惯例。它也不要求正态，更不等于 β。",
  },
  {
    id: "pricing-leverage-001",
    kind: "multi",
    chapter: "pricing",
    sectionId: "risk-vol",
    conceptSlugs: ["leverage", "leverage-ratio", "liquidity"],
    difficulty: 2,
    skill: "recall",
    stem: "许多高夏普策略的真实风险，更接近下列哪些的乘积？（多选）",
    choices: [
      { id: "a", text: "杠杆" },
      { id: "b", text: "拥挤" },
      { id: "c", text: "流动性（能否按模型价退出）" },
      { id: "d", text: "作者的学历" },
    ],
    answer: ["a", "b", "c"],
    explanation:
      "杠杆放大收益、亏损与破产概率，并把中间回撤变成生存问题。拥挤和流动性一起转向时，模型残差不再正交。",
  },
];
