import type { Question } from "./types";

export const probabilityQuestions: Question[] = [
  {
    id: "probability-bayes-001",
    kind: "truefalse",
    chapter: "probability",
    sectionId: "language",
    conceptSlugs: ["bayes-theorem", "p-value"],
    difficulty: 3,
    skill: "trap",
    stem: "回测里策略「赢了所以有效」，等于用高似然直接当成高后验。",
    answer: true,
    explanation:
      "后验 $\\propto$ 似然 $\\times$ 先验。假阳性高、有效策略的先验很小时，一次显著结果仍然很可能是空的。把 $P(\\text{data}\\mid H_1)$ 当成 $P(H_1\\mid\\text{data})$，就是把似然当成后验。",
  },
  {
    id: "probability-conditional-001",
    kind: "single",
    chapter: "probability",
    sectionId: "language",
    conceptSlugs: ["conditional-probability", "bayes-theorem"],
    difficulty: 3,
    skill: "trap",
    stem: "信号报警时策略为真的概率 $P(\\text{真}\\mid\\text{报警})$，一般等于？",
    choices: [
      { id: "a", text: "$P(\\text{报警}\\mid\\text{真})$，因为「能抓到」就是「抓到了就是真的」" },
      { id: "b", text: "必须用贝叶斯：还取决于先验和假阳性，不能从检出率直接读出" },
      { id: "c", text: "等于 p 值" },
      { id: "d", text: "在独立假设下等于联合概率 $P(\\text{真}\\cap\\text{报警})$" },
    ],
    answer: "b",
    explanation:
      "$P(A\\mid B)$ 一般不等于 $P(B\\mid A)$。检出率高只说明似然高；先验很小或假阳性不低时，报警仍可能大多是空的。这不是 p 值，也不是联合概率。",
  },
  {
    id: "probability-correlation-001",
    kind: "truefalse",
    chapter: "probability",
    sectionId: "dependence",
    conceptSlugs: ["correlation", "correlation-coefficient"],
    difficulty: 3,
    skill: "trap",
    stem: "两个收益序列的相关系数 $\\rho=0$，就可以当作它们独立，组合方差写成方差之和。",
    answer: false,
    explanation:
      "$\\rho=0$ 只是没有**线性**共变，还可以有非线性依赖。独立才能把联合拆成边际之积。危机时相关还会跳向 1，用「平时的 $\\rho$」做分散化会低估尾部。",
  },
  {
    id: "probability-monte-carlo-001",
    kind: "single",
    chapter: "probability",
    sectionId: "lln-mc",
    conceptSlugs: ["monte-carlo"],
    difficulty: 2,
    skill: "calculation",
    stem: "普通蒙特卡罗估计期望，抽样相互独立。要把标准误差大约降到现在的 $1/10$，模拟次数大约需要变成？",
    choices: [
      { id: "a", text: "10 倍，因为误差与 $N$ 成反比" },
      { id: "b", text: "100 倍，因为误差大约按 $1/\\sqrt{N}$ 下降" },
      { id: "c", text: "2 倍，中心极限定理会自动补上精度" },
      { id: "d", text: "不用加次数，换一个随机种子即可" },
    ],
    answer: "b",
    explanation:
      "MC 误差大约是 $\\sigma/\\sqrt{N}$。降到 $1/10$ 需要 $\\sqrt{N}$ 变 10 倍，即 $N$ 变 100 倍。方差缩减往往比蛮力加次数更划算；换种子不改变阶数。",
  },
  {
    id: "probability-normal-001",
    kind: "truefalse",
    chapter: "probability",
    sectionId: "expectation",
    conceptSlugs: ["normal-distribution", "empirical-rule"],
    difficulty: 3,
    skill: "trap",
    stem: "日收益若用正态 $\\pm 2\\sigma$ 当「约 95% 不会亏那么多」的风控限额，在危机里通常仍然够用。",
    answer: false,
    explanation:
      "经验法则是正态分布的性质，不是市场事实。日收益通常左偏、厚尾；用 $\\pm 2\\sigma$ 当 95% 限额会在危机里破产。正态是可计算的起点。",
  },
  {
    id: "probability-lln-001",
    kind: "single",
    chapter: "probability",
    sectionId: "lln-mc",
    conceptSlugs: ["law-of-large-numbers"],
    difficulty: 3,
    skill: "trap",
    stem: "把过去十年牛市里某规则的胜率直接当成「以后赢的概率」，主要误用了什么？",
    choices: [
      { id: "a", text: "贝叶斯定理：没有写先验" },
      { id: "b", text: "大数定律：样本既不够独立、也谈不上同一分布" },
      { id: "c", text: "中心极限定理：胜率不是均值" },
      { id: "d", text: "相关系数：没有年化" },
    ],
    answer: "b",
    explanation:
      "大数定律要求 i.i.d. 且期望有限。金融「样本」高度依赖、非平稳；一段牛市的频率不是概率。CLT 说的是均值的渐近分布，不是这段胜率能不能当概率用。",
  },
  {
    id: "probability-joint-001",
    kind: "single",
    chapter: "probability",
    sectionId: "language",
    conceptSlugs: ["joint-probability", "conditional-probability"],
    difficulty: 2,
    skill: "recall",
    stem: "组合在「利率跳升 **且** 信用利差走阔」时的亏损，首先应该用哪一个对象来想？",
    choices: [
      { id: "a", text: "两个边际概率相加" },
      { id: "b", text: "联合分布（或条件于宏观状态的联合）" },
      { id: "c", text: "各自的无条件期望" },
      { id: "d", text: "相关系数 $\\rho$ 本身" },
    ],
    answer: "b",
    explanation:
      "同时发生是联合事件。边际相加会双计、也没有依赖结构。$\\rho$ 只是线性摘要，不是联合分布。链式法则：$P(A\\cap B)=P(A\\mid B)P(B)$。",
  },
  {
    id: "probability-expectation-001",
    kind: "truefalse",
    chapter: "probability",
    sectionId: "expectation",
    conceptSlugs: ["expected-value", "variance"],
    difficulty: 2,
    skill: "trap",
    stem: "一个策略的期望收益为正，就保证按这个期望仓位长期复利不会破产。",
    answer: false,
    explanation:
      "算术期望可以被尾部绑架：正期望仍可因杠杆和方差破产。重复博弈里，几何期望（对数财富）更接近「能不能活着复利」。只报一个均值等于没有模型。",
  },
  {
    id: "probability-covariance-001",
    kind: "single",
    chapter: "probability",
    sectionId: "dependence",
    conceptSlugs: ["covariance", "correlation-coefficient", "beta"],
    difficulty: 2,
    skill: "recall",
    stem: "回归斜率 $\\beta$ 与相关系数 $\\rho$ 的关系，正确的是？",
    choices: [
      { id: "a", text: "$\\beta=\\rho$，所以高相关就是高 $\\beta$" },
      { id: "b", text: "$\\beta=\\rho\\,\\sigma_i/\\sigma_m$，高相关不自动等于可交易暴露" },
      { id: "c", text: "$\\beta=\\rho\\,\\sigma_m/\\sigma_i$" },
      { id: "d", text: "$\\rho=0$ 则 $\\beta$ 无定义" },
    ],
    answer: "b",
    explanation:
      "$\\beta=\\mathrm{Cov}(i,m)/\\mathrm{Var}(m)=\\rho\\,\\sigma_i/\\sigma_m$。波动率比会拆开「一起动」和「谁动得更大」。高相关还要看延迟、成本、稳定性。",
  },
  {
    id: "probability-derivative-001",
    kind: "single",
    chapter: "probability",
    sectionId: "dependence",
    conceptSlugs: ["calculus-derivative", "financial-derivative"],
    difficulty: 3,
    skill: "trap",
    stem: "量化里说「对利率求 derivative」，和「买一个 derivative」，通常分别指？",
    choices: [
      { id: "a", text: "都是期权、期货这类合约" },
      { id: "b", text: "前者是微积分导数（敏感度），后者是金融衍生品合约；两个英文词碰巧一样" },
      { id: "c", text: "前者是期货，后者是期权" },
      { id: "d", text: "前者是久期，后者是凸性" },
    ],
    answer: "b",
    explanation:
      "原文把微积分导数误放到概率章并配上金融衍生品正文。Delta、久期是导数；远期、期权是 derivative security。不要混。",
  },
  {
    id: "probability-variance-001",
    kind: "multi",
    chapter: "probability",
    sectionId: "expectation",
    conceptSlugs: ["variance", "probability-distribution", "normal-distribution"],
    difficulty: 2,
    skill: "recall",
    stem: "只报一个均值、不报分布时，你会丢掉哪些实务上必需的对象？（多选）",
    choices: [
      { id: "a", text: "分位数（如 VaR 用的左尾）" },
      { id: "b", text: "偏度、峰度、尾部厚度" },
      { id: "c", text: "无风险利率的符号" },
      { id: "d", text: "方差 / 波动，以及它是否随时间聚集" },
    ],
    answer: ["a", "b", "d"],
    explanation:
      "定价和风控是在某个分布下求期望、分位数或尾部积分。均值不决定分位数、偏峰和波动聚集。无风险利率的符号与「有没有分布」无关。",
  },
  {
    id: "probability-formula-001",
    kind: "match",
    chapter: "probability",
    sectionId: "language",
    conceptSlugs: ["bayes-theorem", "correlation-coefficient", "monte-carlo", "conditional-probability"],
    difficulty: 1,
    skill: "recall",
    stem: "把公式和它在量化里真正对应的工作对象连起来。",
    left: [
      { id: "bayes", text: "贝叶斯更新" },
      { id: "rho", text: "线性相关" },
      { id: "mc", text: "无解析解的期望" },
      { id: "cond", text: "「已经看见 B」" },
    ],
    right: [
      { id: "bayes", text: "$P(A\\mid B)=P(B\\mid A)P(A)/P(B)$" },
      { id: "rho", text: "$\\rho=\\mathrm{Cov}/(\\sigma_X\\sigma_Y)$" },
      { id: "mc", text: "$\\mathbb{E}[f(X)]\\approx N^{-1}\\sum f(X^{(i)})$" },
      { id: "cond", text: "$P(A\\mid B)=P(A\\cap B)/P(B)$" },
    ],
    pairs: { bayes: "bayes", rho: "rho", mc: "mc", cond: "cond" },
    explanation:
      "条件概率是原子；贝叶斯是它的重写。相关把协方差无量纲化。蒙特卡罗用抽样逼近期望，误差大约 $1/\\sqrt{N}$。",
  },
];
