import type { Question } from "./types";

export const riskQuestions: Question[] = [
  {
    id: "risk-var-001",
    kind: "truefalse",
    chapter: "risk",
    sectionId: "lessons",
    conceptSlugs: ["value-at-risk"],
    difficulty: 3,
    skill: "trap",
    stem: "95% 日 VaR 是「最大可能亏损」，所以没有被 VaR 覆盖的亏损可以忽略。",
    answer: false,
    explanation:
      "VaR 是分位数，不是最大可能亏损。它不说超过它之后会亏多少（那是 ES）。正态假设的 VaR 在厚尾下系统性偏小。95% 日 VaR 意味着平均每月约一天被击穿。",
  },
  {
    id: "risk-ltcm-001",
    kind: "single",
    chapter: "risk",
    sectionId: "lessons",
    conceptSlugs: ["ltcm", "leverage", "liquidity"],
    difficulty: 2,
    skill: "recall",
    stem: "LTCM 教案里，模型「套利」不再是套利，核心机制是？",
    choices: [
      { id: "a", text: "公式写错了，换成 BS 就行" },
      { id: "b", text: "高杠杆相对价值在相关崩溃、融资抽走时，残差不再正交，清算是同步的" },
      { id: "c", text: "他们没有用过回归" },
      { id: "d", text: "只是运气不好，与流动性无关" },
    ],
    answer: "b",
    explanation:
      "模型里的正交在压力下失效。杠杆、拥挤、流动性螺旋是同一件事的三个名字。诺贝尔奖公式救不了融资。",
  },
  {
    id: "risk-drawdown-001",
    kind: "single",
    chapter: "risk",
    sectionId: "lessons",
    conceptSlugs: ["drawdown", "leverage"],
    difficulty: 2,
    skill: "calculation",
    stem: "净值从峰值回撤 50%。要回到旧高，大约需要赚多少？",
    choices: [
      { id: "a", text: "50%" },
      { id: "b", text: "100%" },
      { id: "c", text: "25%" },
      { id: "d", text: "与回撤无关，CAGR 会自动补上" },
    ],
    answer: "b",
    explanation:
      "亏 50% 需要赚 100% 才回本。CAGR 与夏普都看不见回撤。两个年化相同的策略，MDD 20% 与 60% 是完全不同的产品。",
  },
  {
    id: "risk-kelly-001",
    kind: "single",
    chapter: "risk",
    sectionId: "lessons",
    conceptSlugs: ["kelly-criterion", "leverage"],
    difficulty: 2,
    skill: "recall",
    stem: "满凯利仓位在实务上最常见的问题是？",
    choices: [
      { id: "a", text: "它最大化破产概率，所以没人用" },
      { id: "b", text: "波动极大，且假设你确切知道 edge 与方差；估计误差下容易过度下注，故多用分数凯利" },
      { id: "c", text: "凯利不能用于连续收益" },
      { id: "d", text: "凯利等于 VaR" },
    ],
    answer: "b",
    explanation:
      "连续近似 $f^*=(\\mu-r_f)/\\sigma^2$。它最大化长期对数增长，不保证有限期内不破产。½ 或 ¼ 凯利是在买生存率。",
  },
  {
    id: "risk-aaa-001",
    kind: "truefalse",
    chapter: "risk",
    sectionId: "lessons",
    conceptSlugs: ["aaa-rating"],
    difficulty: 3,
    skill: "trap",
    stem: "结构化产品标了 AAA，就可以按无风险债来加杠杆。",
    answer: false,
    explanation:
      "AAA 是意见不是保证。结构化产品的 AAA 是 2008 的反面教材：评级没有消除相关、分层和流动性风险。",
  },
  {
    id: "risk-squeeze-001",
    kind: "truefalse",
    chapter: "risk",
    sectionId: "lessons",
    conceptSlugs: ["short-squeeze", "short-selling", "gamma"],
    difficulty: 2,
    skill: "recall",
    stem: "逼空是空头回补的正反馈，线性风险模型往往会低估它。",
    answer: true,
    explanation:
      "上涨迫使回补，买盘再推高。借券稀缺、流通盘小、期权 Gamma 为正时更剧烈。拥挤度是风险因子，不是轶事。",
  },
  {
    id: "risk-corr-001",
    kind: "single",
    chapter: "risk",
    sectionId: "lessons",
    conceptSlugs: ["correlation", "liquidity", "leverage"],
    difficulty: 2,
    skill: "recall",
    stem: "能杀死组合的，往往不是平均波动，而是？",
    choices: [
      { id: "a", text: "日收益的样本均值" },
      { id: "b", text: "杠杆、拥挤、流动性与相关性同时转向" },
      { id: "c", text: "少报了一个因子的 $R^2$" },
      { id: "d", text: "没有用满凯利" },
    ],
    answer: "b",
    explanation:
      "平静样本里校准的风险数字系统性乐观。大萧条与房价泡沫给出同一机制的宏观版：抵押品下跌 → 去杠杆 → 流动性消失 → 价格再跌。",
  },
  {
    id: "risk-es-001",
    kind: "single",
    chapter: "risk",
    sectionId: "lessons",
    conceptSlugs: ["value-at-risk", "probability-distribution"],
    difficulty: 2,
    skill: "recall",
    stem: "VaR 击穿之后亏多少，应该看什么？",
    choices: [
      { id: "a", text: "还是同一个 VaR，再乘 2" },
      { id: "b", text: "尾部期望（ES / CVaR）或完整的损失分布，而不是再报一个分位数" },
      { id: "c", text: "夏普" },
      { id: "d", text: "股票简称" },
    ],
    answer: "b",
    explanation:
      "VaR 对尾部之后沉默。监管和限额常用 VaR，生存问题要用尾部。击穿频率本身就要回测。",
  },
  {
    id: "risk-spiral-001",
    kind: "multi",
    chapter: "risk",
    sectionId: "lessons",
    conceptSlugs: ["liquidity", "leverage", "housing-bubble", "great-depression"],
    difficulty: 2,
    skill: "recall",
    stem: "抵押品下跌触发的流动性螺旋，通常包括哪些环节？（多选）",
    choices: [
      { id: "a", text: "去杠杆、被迫卖出" },
      { id: "b", text: "流动性消失、价格再跌" },
      { id: "c", text: "评级上调" },
      { id: "d", text: "融资条款收紧" },
    ],
    answer: ["a", "b", "d"],
    explanation:
      "活下来靠的是杠杆上限、拥挤度、融资条款，以及承认非线性。任何只在平静样本里校准的数字都偏乐观。",
  },
  {
    id: "risk-survival-001",
    kind: "truefalse",
    chapter: "risk",
    sectionId: "lessons",
    conceptSlugs: ["leverage", "drawdown", "kelly-criterion"],
    difficulty: 2,
    skill: "recall",
    stem: "杠杆策略的约束是路径：中间一次不可接受的回撤，可以在期望仍为正时结束游戏。",
    answer: true,
    explanation:
      "正期望不是生存证明。保证金、赎回、PB 追保都是路径依赖。仓位规则必须先让你活过尾部。",
  },
];
