import type { Question } from "./types";

export const statisticsQuestions: Question[] = [
  {
    id: "statistics-sharpe-001",
    kind: "single",
    chapter: "statistics",
    sectionId: "testing",
    conceptSlugs: ["sharpe-ratio", "t-test"],
    difficulty: 2,
    skill: "calculation",
    stem: "某策略样本内年化夏普为 2，独立样本大约 3 年。用 $t \\approx \\mathrm{Sharpe}\\times\\sqrt{T}$ 粗算，t 统计量最接近？",
    choices: [
      { id: "a", text: "$2$，夏普本身就是 t" },
      { id: "b", text: "$2\\sqrt{3}\\approx 3.5$" },
      { id: "c", text: "$2\\sqrt{252}\\approx 32$，必须先把年化拆回交易日" },
      { id: "d", text: "$2\\times 3=6$" },
    ],
    answer: "b",
    explanation:
      "数量级上 $t \\approx \\text{年化夏普}\\times\\sqrt{\\text{年数}}$，这里 $T=3$ 年，故 $2\\sqrt{3}\\approx 3.46$。不要把已经年化的夏普再乘 $\\sqrt{252}$；也不是把年数直接乘上去。即便 t 看起来「显著」，没有独立样本和成本仍可能是过拟合。",
  },
  {
    id: "statistics-pvalue-001",
    kind: "truefalse",
    chapter: "statistics",
    sectionId: "testing",
    conceptSlugs: ["p-value", "hypothesis-testing"],
    difficulty: 3,
    skill: "trap",
    stem: "p 值是「策略为真的概率」，所以 p=0.01 表示有 99% 把握这套规则能赚钱。",
    answer: false,
    explanation:
      "p 值是：若 $H_0$ 为真，眼前这份数据有多极端。它不是 $P(H_0\\mid\\text{data})$，不是效应大小，更不是「能赚钱的概率」。",
  },
  {
    id: "statistics-significance-001",
    kind: "single",
    chapter: "statistics",
    sectionId: "testing",
    conceptSlugs: ["statistical-significance", "sharpe-ratio"],
    difficulty: 3,
    skill: "trap",
    stem: "一个因子在样本里统计显著。接下来最应该补上的是？",
    choices: [
      { id: "a", text: "到此为止：显著就是能交易" },
      { id: "b", text: "看经济显著性——扣成本、容量、衰减；并问多重检验有没有把 p 值作废" },
      { id: "c", text: "把 p 值改写成胜率" },
      { id: "d", text: "加大杠杆直到夏普看起来更高" },
    ],
    answer: "b",
    explanation:
      "统计显著只说明不像纯噪声。样本越大，越小的效应也会显著。先看数据再选假设，p 值作废；多个因子一起挖必须做多重检验校正。",
  },
  {
    id: "statistics-ci-001",
    kind: "truefalse",
    chapter: "statistics",
    sectionId: "testing",
    conceptSlugs: ["confidence-interval"],
    difficulty: 3,
    skill: "trap",
    stem: "已经算出来的 95% 置信区间，意思是「这个具体区间里有 95% 概率装着真值」。",
    answer: false,
    explanation:
      "频率派的 95% 是：重复实验时，这类区间覆盖真值的比例。对**已经实现**的那一个区间，真值要么在里面要么不在，没有 95% 这个概率。许多「年化 20%」的区间其实穿过 0。",
  },
  {
    id: "statistics-rsquared-001",
    kind: "truefalse",
    chapter: "statistics",
    sectionId: "regression",
    conceptSlugs: ["r-squared", "multiple-regression"],
    difficulty: 2,
    skill: "trap",
    stem: "多元回归里每加一个解释变量，$R^2$ 都不会下降，所以应该用 $R^2$ 决定要不要加因子。",
    answer: false,
    explanation:
      "加变量 $R^2$ 只升不降，所以看调整 $R^2$；预测看样本外。高 $R^2$ 也可以来自共同趋势或过拟合。一元时 $R^2=\\rho^2$。",
  },
  {
    id: "statistics-multicol-001",
    kind: "single",
    chapter: "statistics",
    sectionId: "regression",
    conceptSlugs: ["multicollinearity", "variance-inflation-factor"],
    difficulty: 2,
    skill: "recall",
    stem: "因子回归里每个系数都不显著、符号乱跳，但整体拟合仍然很好。最像什么？",
    choices: [
      { id: "a", text: "数据没有线性关系，应改用分类树" },
      { id: "b", text: "共线性：单个系数不稳，整体仍可解释共同变化；VIF 是诊断不是策略" },
      { id: "c", text: "异方差，必须立刻换成 GARCH 交易" },
      { id: "d", text: "说明 $\\alpha$ 显著，可以加杠杆" },
    ],
    answer: "b",
    explanation:
      "共线性让 $(X^\\top X)^{-1}$ 病态，单个 $\\beta$ 方差爆炸，但共同空间仍可拟合。VIF 帮你看见这件事，它本身不是可交易信号。",
  },
  {
    id: "statistics-clt-001",
    kind: "single",
    chapter: "statistics",
    sectionId: "clt",
    conceptSlugs: ["central-limit-theorem", "normal-distribution"],
    difficulty: 2,
    skill: "recall",
    stem: "中心极限定理让大样本均值看起来像正态。下列哪一种情况最容易让它失效或变得极慢？",
    choices: [
      { id: "a", text: "样本量超过 30" },
      { id: "b", text: "方差无限或尾部极厚，或样本强烈依赖却仍当 i.i.d." },
      { id: "c", text: "回归里用了多个因子" },
      { id: "d", text: "收益已经年化" },
    ],
    answer: "b",
    explanation:
      "CLT 要独立、方差有限。日收益「有限方差」本身就可疑；有依赖时要用混合中心极限或 HAC，不能假装 i.i.d.。n=30 是口诀不是定理。",
  },
  {
    id: "statistics-autocorr-001",
    kind: "truefalse",
    chapter: "statistics",
    sectionId: "regression",
    conceptSlugs: ["autocorrelation", "heteroskedasticity"],
    difficulty: 3,
    skill: "trap",
    stem: "用重叠的滚动月收益做回归，名义 t 统计量仍然可以直接当独立样本来用。",
    answer: false,
    explanation:
      "重叠窗口会人为制造巨大自相关，OLS 标准误作废，名义 t 过于乐观。至少用 HAC 或 bootstrap。波动聚集则是平方收益的自相关：方向难测，$\\sigma$ 往往可测。",
  },
  {
    id: "statistics-merton-001",
    kind: "truefalse",
    chapter: "statistics",
    sectionId: "regression",
    conceptSlugs: ["merton-model"],
    difficulty: 3,
    skill: "trap",
    stem: "默顿模型是一种统计检验，用来判断股票收益是否服从正态。",
    answer: false,
    explanation:
      "默顿把公司股权写成企业资产的看涨期权，是结构信用模型，不是正态性检验。原文放错章节；公式里的 $\\sigma$ 是资产波动 $\\sigma_V$，不是股票波动。",
  },
  {
    id: "statistics-ols-001",
    kind: "single",
    chapter: "statistics",
    sectionId: "regression",
    conceptSlugs: ["ols", "regression", "capm"],
    difficulty: 2,
    skill: "recall",
    stem: "CAPM $\\beta$、对冲比率、Fama–French 归因，第一版通常都是在做什么？",
    choices: [
      { id: "a", text: "最大化 $R^2$ 的非线性搜索" },
      { id: "b", text: "OLS：选使残差平方和最小的系数" },
      { id: "c", text: "对收益做主成分，强制第一因子为市场" },
      { id: "d", text: "用凯利公式决定仓位，再叫它 $\\beta$" },
    ],
    answer: "b",
    explanation:
      "$\\hat\\beta=(X^\\top X)^{-1}X^\\top Y$。归因就是回归。把未来信息放进 $X$ 则是前视偏差。",
  },
  {
    id: "statistics-lookahead-001",
    kind: "single",
    chapter: "statistics",
    sectionId: "regression",
    conceptSlugs: ["regression", "backtesting"],
    difficulty: 3,
    skill: "trap",
    stem: "用「当季已公布的财报」去解释「该季已经实现的收益」，最像哪种错误？",
    choices: [
      { id: "a", text: "异方差，换稳健标准误即可" },
      { id: "b", text: "前视偏差：把当时还不可获得的信息放进了 $X$" },
      { id: "c", text: "共线性，删掉一个因子" },
      { id: "d", text: "没有年化" },
    ],
    answer: "b",
    explanation:
      "回归系数是「控制其他变量后」的偏效应。时间轴上不可得的 $X$ 会把回测变成故事。稳健标准误修不了信息集错误。",
  },
  {
    id: "statistics-hyp-001",
    kind: "multi",
    chapter: "statistics",
    sectionId: "testing",
    conceptSlugs: ["hypothesis-testing", "t-test", "sharpe-ratio"],
    difficulty: 2,
    skill: "recall",
    stem: "收益厚尾、异方差、重叠窗口时，名义 t 过于乐观。实务上更诚实的做法包括？（多选）",
    choices: [
      { id: "a", text: "HAC 标准误或 bootstrap" },
      { id: "b", text: "把夏普乘以 2 当作「真实夏普」" },
      { id: "c", text: "报告置信区间，而不是只报一个点夏普" },
      { id: "d", text: "样本外、扣成本后再谈显著" },
    ],
    answer: ["a", "c", "d"],
    explanation:
      "t 检验在方差未知时用样本 $\\sigma$，但金融收益很少满足教科书假设。区间比单点诚实；样本外和成本才对得上「能不能用」。没有「夏普×2」这种校正。",
  },
];
