import type { Question } from "./types";

export const strategiesQuestions: Question[] = [
  {
    id: "strategies-neutral-001",
    kind: "truefalse",
    chapter: "strategies",
    sectionId: "relative",
    conceptSlugs: ["market-neutral", "long-short-equity"],
    difficulty: 3,
    skill: "trap",
    stem: "多空金额各一半，就是市场中性。",
    answer: false,
    explanation:
      "中性是对实现 β 与因子回归检验的结果，不是金额各半。市值中性 ≠ β 中性 ≠ 因子中性。危机中残差相关仍可让「中性」大亏。",
  },
  {
    id: "strategies-momentum-001",
    kind: "single",
    chapter: "strategies",
    sectionId: "ts",
    conceptSlugs: ["momentum", "trend-trading"],
    difficulty: 2,
    skill: "recall",
    stem: "横截面动量作为因子，最需要记住的风险是？",
    choices: [
      { id: "a", text: "它从未失效，所以可以满仓" },
      { id: "b", text: "它是最稳健的因子之一，但有崩溃（momentum crash）" },
      { id: "c", text: "动量就是均线，没有崩溃" },
      { id: "d", text: "动量只存在于日频，与月频无关" },
    ],
    answer: "b",
    explanation:
      "过去强者继续强，是实证上很顽强的溢价；反转发生时亏损集中。趋势（时序）与动量（横截面）不是同一个过滤器。",
  },
  {
    id: "strategies-mr-001",
    kind: "truefalse",
    chapter: "strategies",
    sectionId: "ts",
    conceptSlugs: ["mean-reversion"],
    difficulty: 3,
    skill: "trap",
    stem: "价格跌多了就该买：随机游走也是均值回归，只是回归得慢。",
    answer: false,
    explanation:
      "均值回归是负自相关或平稳过程。均衡会走，把随机游走当回归就是接飞刀。三者可以共存：短期噪声回归、中期趋势、长期估值回归——必须先定义尺度。",
  },
  {
    id: "strategies-backtest-001",
    kind: "multi",
    chapter: "strategies",
    sectionId: "research",
    conceptSlugs: ["backtesting", "alpha"],
    difficulty: 3,
    skill: "trap",
    stem: "回测把夏普从 2 打到 0，常见原因包括？（多选）",
    choices: [
      { id: "a", text: "前视偏差、幸存者偏差" },
      { id: "b", text: "遗漏成本、无限卖空" },
      { id: "c", text: "过拟合与多重检验" },
      { id: "d", text: "作者没有引用利弗莫尔" },
    ],
    answer: ["a", "b", "c"],
    explanation:
      "用当时可获得的信息模拟规则。任意一条敌人都可以把故事夏普打穿。利弗莫尔是市场文化，不是数据集。",
  },
  {
    id: "strategies-carry-001",
    kind: "truefalse",
    chapter: "strategies",
    sectionId: "relative",
    conceptSlugs: ["carry-trade"],
    difficulty: 3,
    skill: "trap",
    stem: "利差交易赚利率差，因为有抛补利率平价，所以这是套利。",
    answer: false,
    explanation:
      "利差交易赚利率差、承担汇率崩塌，是负偏风险溢价，不是套利。套利者的资本有限，所以偏差可以持续。",
  },
  {
    id: "strategies-horizon-001",
    kind: "single",
    chapter: "strategies",
    sectionId: "ts",
    conceptSlugs: ["trend-trading", "momentum", "mean-reversion"],
    difficulty: 2,
    skill: "recall",
    stem: "趋势、动量、均值回归看起来互相矛盾。更准确的说法是？",
    choices: [
      { id: "a", text: "只能存在一个，必须用假设检验选出赢家" },
      { id: "b", text: "它们可以在不同时间尺度共存" },
      { id: "c", text: "都是均线的别名" },
      { id: "d", text: "只有日线有效" },
    ],
    answer: "b",
    explanation:
      "短期噪声回归、中期趋势、长期估值回归可以同时成立。均线、黄金交叉、RSI 只是这些结构的滤波器，必须定义成可程序化规则再测。",
  },
  {
    id: "strategies-short-bt-001",
    kind: "truefalse",
    chapter: "strategies",
    sectionId: "research",
    conceptSlugs: ["backtesting", "short-selling"],
    difficulty: 3,
    skill: "trap",
    stem: "多空回测里假设任何股票都能按收盘价无限卖空，只影响执行细节，不改变策略是否成立。",
    answer: false,
    explanation:
      "借券、召回、禁止卖空名单会直接删掉空腿。这不是执行细节，是 alpha 还在不在的问题。",
  },
  {
    id: "strategies-pairs-001",
    kind: "single",
    chapter: "strategies",
    sectionId: "ts",
    conceptSlugs: ["pairs-trading", "mean-reversion"],
    difficulty: 2,
    skill: "recall",
    stem: "配对交易在经济上首先是？",
    choices: [
      { id: "a", text: "两只股票各买一半，自动市场中性" },
      { id: "b", text: "对价差的均值回归（或协整）下注，对冲的是共同因子而不是金额" },
      { id: "c", text: "无条件套利" },
      { id: "d", text: "只在期货里存在" },
    ],
    answer: "b",
    explanation:
      "价差可以走，协整可以断。金额各半仍然可以留下巨大 β。配对是相对价值，不是锁定价差的套利。",
  },
  {
    id: "strategies-multiple-001",
    kind: "single",
    chapter: "strategies",
    sectionId: "research",
    conceptSlugs: ["backtesting", "p-value", "statistical-significance"],
    difficulty: 2,
    skill: "recall",
    stem: "在同一数据集上挖了 100 个因子再报告最小的 p 值，主要问题是？",
    choices: [
      { id: "a", text: "计算机太慢" },
      { id: "b", text: "多重检验：这个 p 值不再对应「只做了一次检验」的假阳性控制" },
      { id: "c", text: "必须改用贝叶斯，频率派不能用" },
      { id: "d", text: "只要夏普大于 2 就可以忽略" },
    ],
    answer: "b",
    explanation:
      "先看数据再选假设，p 值作废。样本外、纸交易、预先登记检验，是实验室纪律，不是可选装饰。",
  },
  {
    id: "strategies-hft-001",
    kind: "truefalse",
    chapter: "strategies",
    sectionId: "relative",
    conceptSlugs: ["hft", "bid-ask"],
    difficulty: 2,
    skill: "recall",
    stem: "即便你不是高频交易者，HFT 仍然在塑造你看到的价差与能否成交。",
    answer: true,
    explanation:
      "你的执行发生在订单簿上。冲击、队列、IOC 与裁量，决定 alpha 还能剩多少。新闻交易在液态品种上已很难赢过机器。",
  },
];
