import type { Question } from "./types";

export const valuationQuestions: Question[] = [
  {
    id: "valuation-log-001",
    kind: "single",
    chapter: "valuation",
    sectionId: "tvm",
    conceptSlugs: ["log-return", "annual-return", "cagr"],
    difficulty: 3,
    skill: "trap",
    stem: "对数收益与简单收益，实务上最容易用错的一点是？",
    choices: [
      { id: "a", text: "二者永远相等，可以随便换" },
      { id: "b", text: "对数收益时间上可加，是统计默认；组合加权仍要用简单收益" },
      { id: "c", text: "组合加权必须用对数收益，否则无法年化" },
      { id: "d", text: "只有债券才用对数收益" },
    ],
    answer: "b",
    explanation:
      "原文几乎没区分。统计、随机微积分爱用对数收益；组合、业绩归因的权重加总必须用简单收益。口径不统一，夏普也不可比。",
  },
  {
    id: "valuation-cagr-001",
    kind: "single",
    chapter: "valuation",
    sectionId: "tvm",
    conceptSlugs: ["cagr", "annual-return"],
    difficulty: 2,
    skill: "calculation",
    stem: "某策略两年净值从 100 到 144。下列哪一个才是这两年的 CAGR？",
    choices: [
      { id: "a", text: "44%，把总收益当年化" },
      { id: "b", text: "$\\sqrt{1.44}-1=20%$" },
      { id: "c", text: "月均收益 × 12（算术年化）" },
      { id: "d", text: "$\\ln(1.44)\\approx 36%$" },
    ],
    answer: "b",
    explanation:
      "CAGR 是几何年化：$(144/100)^{1/2}-1=0.20$。算术「月收益×12」会高估可实现财富；对数 $0.364$ 是连续复合，不是这两年的 CAGR。CAGR 抹掉路径。",
  },
  {
    id: "valuation-pv-001",
    kind: "single",
    chapter: "valuation",
    sectionId: "tvm",
    conceptSlugs: ["present-value", "discount-rate-dcf"],
    difficulty: 2,
    skill: "recall",
    stem: "现值公式 $\\mathrm{PV}=\\sum_t C_t/(1+r)^t$ 里，贴现率 $r$ 必须匹配的是？",
    choices: [
      { id: "a", text: "任意一个市场利率，只要是正数" },
      { id: "b", text: "现金流的风险（例如股权用股权成本，企业自由现金流用 WACC）" },
      { id: "c", text: "美联储贴现窗口利率" },
      { id: "d", text: "上一年的 GDP 增速" },
    ],
    answer: "b",
    explanation:
      "贴现率必须匹配现金流风险。宏观利率通过这条通道进入成长股，但不能拿窗口利率或 GDP 顶替风险调整折现。",
  },
  {
    id: "valuation-pe-001",
    kind: "truefalse",
    chapter: "valuation",
    sectionId: "multiples",
    conceptSlugs: ["pe-ratio"],
    difficulty: 2,
    skill: "recall",
    stem: "在 Gordon 增长模型下，P/E 大约是 $1/(r-g)$；公司亏损时这个倍数仍然有意义。",
    answer: false,
    explanation:
      "前半句是隐藏假设的模型。亏损时分母为负或近零，P/E 无意义。还要用总回报：忽略股息会低估股票。",
  },
  {
    id: "valuation-dilution-001",
    kind: "single",
    chapter: "valuation",
    sectionId: "multiples",
    conceptSlugs: ["dilution", "share-issuance"],
    difficulty: 2,
    skill: "recall",
    stem: "看估值倍数时，为什么要看 fully diluted？",
    choices: [
      { id: "a", text: "因为交易所规则要求" },
      { id: "b", text: "增发、期权、转债会摊薄现有股东对资产的索取权" },
      { id: "c", text: "稀释只会提高 EPS，使 P/E 更好看" },
      { id: "d", text: "只对债券持有人有影响" },
    ],
    answer: "b",
    explanation:
      "股权是剩余索取权。不看摊薄，就是在用「现在的股数」去除「以后别人也有份的利润」。",
  },
  {
    id: "valuation-equity-call-001",
    kind: "truefalse",
    chapter: "valuation",
    sectionId: "corp",
    conceptSlugs: ["lbo", "merton-model"],
    difficulty: 2,
    skill: "recall",
    stem: "高杠杆之后，股权在经济上更像企业资产上的看涨期权：上行无限、下行以股权为限。",
    answer: true,
    explanation:
      "LBO 把股权压成薄薄一层期权。默顿模型把这件事写成公式。债务重组是优先级之间重新分配损失，不是债务消失。",
  },
  {
    id: "valuation-cape-001",
    kind: "single",
    chapter: "valuation",
    sectionId: "multiples",
    conceptSlugs: ["cape", "pe-ratio"],
    difficulty: 3,
    skill: "trap",
    stem: "CAPE（周期调整市盈率）最适合用来？",
    choices: [
      { id: "a", text: "做下周择时" },
      { id: "b", text: "十年尺度的配置直觉；对短择时很弱" },
      { id: "c", text: "替代贴现率" },
      { id: "d", text: "判断单只亏损公司是否便宜" },
    ],
    answer: "b",
    explanation:
      "CAPE 用十年实际盈利平滑周期。它是慢变量。把 CAPE 当短线信号，是把配置工具当成交易法则。",
  },
  {
    id: "valuation-compound-001",
    kind: "single",
    chapter: "valuation",
    sectionId: "tvm",
    conceptSlugs: ["compounding", "present-value"],
    difficulty: 2,
    skill: "calculation",
    stem: "年利率 10%，连续复利一年，终值因子最接近？",
    choices: [
      { id: "a", text: "$1.10$" },
      { id: "b", text: "$e^{0.10}\\approx 1.1052$" },
      { id: "c", text: "$1.10^{12}$" },
      { id: "d", text: "$\\ln(1.10)\\approx 0.095$" },
    ],
    answer: "b",
    explanation:
      "复利频率趋向连续时变成 $e^{rt}$。年复利一次是 $1.10$；连续略高。$\\ln(1.10)$ 是反过来把年复利换成连续利率，不是终值因子。",
  },
  {
    id: "valuation-growth-001",
    kind: "truefalse",
    chapter: "valuation",
    sectionId: "multiples",
    conceptSlugs: ["growth-rate", "growth-curve", "pe-ratio"],
    difficulty: 3,
    skill: "trap",
    stem: "把最近几年的高增长外推成永续 g，再代入 $1/(r-g)$，是估值里常见且危险的做法。",
    answer: true,
    explanation:
      "增长曲线往往从指数变为 S 形。g 接近 r 时倍数爆炸，模型在惩罚你把短暂繁荣写成永续。",
  },
  {
    id: "valuation-ma-001",
    kind: "single",
    chapter: "valuation",
    sectionId: "corp",
    conceptSlugs: ["ma-deals"],
    difficulty: 2,
    skill: "recall",
    stem: "事件驱动里的并购价差，经济上最接近？",
    choices: [
      { id: "a", text: "无风险套利，因为公告价已锁定" },
      { id: "b", text: "成交概率 × 时间价值 − 断单风险" },
      { id: "c", text: "目标公司的历史波动率" },
      { id: "d", text: "收购方的 P/E" },
    ],
    answer: "b",
    explanation:
      "价差不是免费午餐。融资、监管、竞标失败都会把「锁定」打开。把它当无风险，和 LTCM 把相对价值当套利是同一类错误。",
  },
];
